var mongoose = require("mongoose");
var Schema = mongoose.Schema;
var EmployeeSchema = new Schema({
    employeeid: String,
    password: String,
    username: String,
    firstname: String,
    middlename: String,
    lastname: String,
    employeetype: String,
    desigination: String,
    practice: String,
    officeemail: String,
    department: String,
    personalemail: String,
    reportingmanager: String,
    reportinmanageremail: String,
    mentor: String,
    dob: Date,
    joiningdate: Date,
    careerstartingdate: Date,
    adhar: String,
    pan: String,
    passport: String,
    sex: String,
    marraige: String,
    bloodgroup: String,
    presentadd: String,
    premenantadd: String,
    extension: String,
    phonenumber: String,
    createddate: Date,
    jobstatus: String,
    emailverified: String,
    imageURL: String,
    adminaccess: Boolean,
    manager: Boolean,
    projects: Array,
    helathinsurance: Array,
    skills: Array,
    previousexpreince: Array,
    itassets: Array,
    leaves: Array,
    fresher: Boolean,
    itadmin: Boolean
});
module.exports = EmployeeSchema